// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\roger\Documents\RS-SISTEMAS-2022\Aplicações\crud-go\internal\model\user_domain.go
//
// Generated by this command:
//
//	mockgen.exe -source=C:\Users\roger\Documents\RS-SISTEMAS-2022\Aplicações\crud-go\internal\model\user_domain.go -destination=C:\Users\roger\Documents\RS-SISTEMAS-2022\Aplicações\crud-go\internal\tests\mocks\user_domain_mock.go -package=mocks
//
// Package mocks is a generated GoMock package.
package mocks
